language: python
services:
  - postgresql
  - redis-server
python:
  - "2.7"
before_script:
- export DATABASE_URL=postgres://postgres@localhost/bare-travel
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c 'CREATE DATABASE "bare-travel";' -U postgres
install:
  - "pip install -r requirements/test.txt"
script:
  - ./bare-travel/manage.py test bare-travel
after_success:
  - coveralls

deploy:
  provider: heroku
  app:
    master: bare-travel-dev
    qa: bare-travel-qa
    prod: bare-travel-prod
  on:
    repo: garybutton/bare-travel-api
  run:
    - "./bare-travel/manage.py migrate"

notifications:
  email: false

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
  fast_finish: true
